language: python
services:
  - xvfb
  - mysql
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "git fetch origin master:pylint-basis"
    - "git diff pylint-basis --name-only  -- '*.py' > CHANGED_PY_FILES"
# This is workaround for bug https://code.djangoproject.com/ticket/25329;
# you might remove this line after upgrade to django 1.8+
    - mysql -e 'set global wait_timeout=3600'
install:
    - "pip install -e git://github.com/edx/xblock-sdk.git@bddf9f4a2c6e4df28a411c8f632cc2250170ae9d#egg=xblock-sdk"
    - "pip install -r requirements.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/base.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/test.txt"
    - "pip install --ignore-installed -r test_requirements.txt"
    - "pip install mysqlclient"
# Install sa known selenium version, so we get reproducibility
    - pip install selenium==2.50.1
script:
    - pep8 mentoring --max-line-length=120
    # Run pylint on any modified .py files but since there are a lot of issues right now, don't make it fail the build:
    - "[ -s CHANGED_PY_FILES ] && (cat CHANGED_PY_FILES | xargs pylint || echo -e \\\\nWARNING: PYLINT ERRORS) || echo pylint skipped"
    - python tests/manage.py test --rednose --settings=settings_travis --noinput
notifications:
  email: false
addons:
  firefox: "38.0"
